version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolyo_app
    restart: always
    ports:
      - "2892:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
